INSERT INTO players (name, club)
  VALUES
  ('John', 'MTL'),
  ('Sarah', 'OTT'),
  ('Alex', 'CGY'),
  ('John', 'MTL'),
  ('Sarah', 'OTT'),
  ('Alex', 'CGY'),
  ('John', 'MTL'),
  ('Sarah', 'OTT'),
  ('Alex', 'CGY'),
  ('John', 'MTL'),
  ('Sarah', 'OTT'),
  ('Alex', 'CGY'),
  ('John', 'MTL'),
  ('Sarah', 'OTT'),
  ('Alex', 'CGY'),
  ('John', 'MTL'),
  ('Sarah', 'OTT'),
  ('Alex', 'CGY');
