DROP TABLE IF EXISTS groups CASCADE;
CREATE TABLE groups (
  id SERIAL PRIMARY KEY NOT NULL,
  tournament_id INTEGER REFERENCES tournaments(id) ON DELETE CASCADE,
  team_1 INTEGER REFERENCES teams(id) ON DELETE CASCADE,
  team_2 INTEGER REFERENCES teams(id) ON DELETE CASCADE,
  team_3 INTEGER REFERENCES teams(id) ON DELETE CASCADE,
  team_4 INTEGER REFERENCES teams(id) ON DELETE CASCADE,
  team_5 INTEGER REFERENCES teams(id) ON DELETE CASCADE,
  team_6 INTEGER REFERENCES teams(id) ON DELETE CASCADE,
  team_7 INTEGER REFERENCES teams(id) ON DELETE CASCADE,
  team_8 INTEGER REFERENCES teams(id) ON DELETE CASCADE,
  team_9 INTEGER REFERENCES teams(id) ON DELETE CASCADE,
  team_10 INTEGER REFERENCES teams(id) ON DELETE CASCADE,
  team_11 INTEGER REFERENCES teams(id) ON DELETE CASCADE,
  team_12 INTEGER REFERENCES teams(id) ON DELETE CASCADE
);

