DROP TABLE IF EXISTS matches CASCADE;
CREATE TABLE matches (
  id SERIAL PRIMARY KEY NOT NULL,
  tournament_id INTEGER REFERENCES tournaments(id) ON DELETE CASCADE,
  group_id INTEGER,
  team_1 INTEGER REFERENCES teams(id) ON DELETE CASCADE,
  team_2 INTEGER REFERENCES teams(id) ON DELETE CASCADE,
  winner INTEGER REFERENCES teams(id) ON DELETE CASCADE
);
